sudo: required
dist: trusty
language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: jonas.birme@eyevinn.se
  api_key:
    secure: p0LHnOJyaeTrpZiQAAvHo8kkgbPQU6RayjavmxaB/D/e7tTJYBZgHqfKkTZA3bU3vlkCT05KF2d6xsuHsJSrK4JD5BmDA0B7qio2qfFFWiGAiAB4NcMk12ftr/VND3N3bPXvdUsGfj6g27wNwoSnBfkcmnw7aiFQz8/dEpVhCxGaOWBURhH4ZuLWgBk/3aGBN3fJ4l9PZ7OZVs2dRinDOWIzdXr5rBRB/HGVY1kg2lIyGgP6csmVDIvj54UervlbXzh+2pfx9ATsWqTINCIW47lowICz+xOCZqU9ziu/IM51AUcfixemvx9KmPDREWIrjCRmUpmV8Sfr2Q4NjQQqHdkYResITyIm8e/mC+57i2YTOr1QLxckcSq9wd2GqQ1u4MuFcocoRWbK/A7e2Mv/Xd0Nqb1Tg4YK8oLC80OpJJh9a/U4Oq+HZ/i2PDVaiQAYXf8xCkTBl/fPXJAuf6yzhq5LhHtxJc/Q//jukHJV+w2QD7QnQhGpcYkNzHbR3j6eLlYkAXSpTntDzrG+BLZdlKt24G0R7j5YcNbjYfEXHJeEMEUR2uLUv+3bJ+D+WQAOzFIg8LR0QKSVVmrpdde/3ILewRpfkgvYNL7qqvJoPc+NKC28jg2W1IxLfmvk6e3fx737DONymvJcrgNLpN8vFt+I4lfPc9d/R6LnqJuzP6s=
  on:
    tags: true
    repo: Eyevinn/channel-engine

